namespace Object  // capitalized since Object is a keyword in C# (autogenerated @object)
{
    using System.Collections.Generic;
    using ObjectType = System.String;

    // used List<> instead of params
    delegate Object BuiltinFunction(List<Object> args);

    struct _ObjectType // Workaround
    {
        public const ObjectType NULL_OBJ = "NULL";
        public const ObjectType ERROR_OBJ = "ERROR";

        public const ObjectType INTEGER_OBJ = "INTEGER";
        public const ObjectType BOOLEAN_OBJ = "BOOLEAN";
        public const ObjectType STRING_OBJ = "STRING";

        public const ObjectType RETURN_VALUE_OBJ = "RETURN_VALUE";

        public const ObjectType FUNCTION_OBJ = "FUNCTION";
        public const ObjectType BUILTIN_OBJ = "BUILTIN";

        public const ObjectType ARRAY_OBJ = "ARRAY";
        public const ObjectType HASH_OBJ = "HASH";

        public const ObjectType QUOTE_OBJ = "QUOTE";
        public const ObjectType MACRO_OBJ = "MACRO";
    }

    struct HashKey
    {
        public ObjectType Type;
        public long Value;
    }

    interface Hashable
    {
        HashKey HashKey();
    }

    interface Object
    {
        ObjectType Type();
        string Inspect();
    }

    struct Integer : Object, Hashable
    {
        public long Value;

        public ObjectType Type() { return _ObjectType.INTEGER_OBJ; }
        public string Inspect() { return Value.ToString(); }
        public HashKey HashKey()
        {
            return new HashKey { Type = this.Type(), Value = (long)this.Value };
        }
    }

    struct Boolean : Object, Hashable
    {
        public bool Value;

        public ObjectType Type() { return _ObjectType.BOOLEAN_OBJ; }
        public string Inspect() { return Value.ToString(); }
        public HashKey HashKey()
        {
            long value;

            if (this.Value)
            {
                value = 1;
            }
            else
            {
                value = 0;
            }
            return new HashKey { Type = this.Type(), Value = value };
        }
    }

    struct Null : Object
    {
        public ObjectType Type() { return _ObjectType.NULL_OBJ; }
        public string Inspect() { return "null"; }
    }

    struct ReturnValue : Object
    {
        public Object Value;

        public ObjectType Type() { return _ObjectType.RETURN_VALUE_OBJ; }
        public string Inspect() { return this.Value.Inspect(); }
    }

    struct Error : Object
    {
        public string Message;

        public ObjectType Type() { return _ObjectType.ERROR_OBJ; }
        public string Inspect() { return "ERROR: " + this.Message; }
    }

    struct Function : Object
    {
        public List<ast.Identifier> Parameters;
        public ast.BlockStatement Body;
        public Environment Env;

        public ObjectType Type() { return _ObjectType.FUNCTION_OBJ; }
        public string Inspect()
        {
            System.Text.StringBuilder out_ = new System.Text.StringBuilder();

            List<string> params_ = new List<string>();
            foreach (ast.Identifier p in this.Parameters)
            {
                params_.Add(p.String());
            }

            out_.Append("fn");
            out_.Append("(");
            out_.Append(string.Join(", ", params_));
            out_.Append(") {\n");
            out_.Append(this.Body.String());
            out_.Append("\n}");

            return out_.ToString();
        }
    }

    struct String : Object, Hashable
    {
        public string Value;

        public ObjectType Type() { return _ObjectType.STRING_OBJ; }
        public string Inspect() { return this.Value; }
        public HashKey HashKey()
        {
            long h = util.hash.hashString(this.Value); // using hash from CLOXCS
            return new HashKey { Type = this.Type(), Value = h };
        }
    }

    struct Builtin : Object
    {
        public BuiltinFunction Fn;

        public ObjectType Type() { return _ObjectType.BUILTIN_OBJ; }
        public string Inspect() { return "builtin function"; }
    }

    struct Array : Object
    {
        public List<Object> Elements;

        public ObjectType Type() { return _ObjectType.ARRAY_OBJ; }
        public string Inspect()
        {
            System.Text.StringBuilder out_ = new System.Text.StringBuilder();

            List<string> elements = new List<string>();
            foreach (Object e in this.Elements)
            {
                elements.Add(e.Inspect());
            }

            out_.Append("[");
            out_.Append(string.Join(", ", elements));
            out_.Append("]");

            return out_.ToString();
        }
    }

    struct HashPair
    {
        public Object Key;
        public Object Value;
    }

    struct Hash : Object
    {
        public Dictionary<HashKey, HashPair> Pairs;

        public ObjectType Type() { return _ObjectType.HASH_OBJ; }
        public string Inspect()
        {
            System.Text.StringBuilder out_ = new System.Text.StringBuilder();

            List<string> pairs = new List<string>();
            foreach (KeyValuePair<HashKey, HashPair> pair in this.Pairs)
            {
                pairs.Add(string.Format("{0}: {1}", pair.Value.Key.Inspect(), pair.Value.Value.Inspect()));
            }

            out_.Append("{");
            out_.Append(string.Join(", ", pairs));
            out_.Append("}");

            return out_.ToString();
        }
    }

    struct Quote : Object
    {
        public ast.Node Node;

        public ObjectType Type() { return _ObjectType.QUOTE_OBJ; }
        public string Inspect() { return "QUOTE(" + this.Node.String() + ")"; }
    }

    class Macro : Object // class to be nullable
    {
        public List<ast.Identifier> Parameters;
        public ast.BlockStatement Body;
        public Environment Env;

        public ObjectType Type() { return _ObjectType.MACRO_OBJ; }
        public string Inspect()
        {
            System.Text.StringBuilder out_ = new System.Text.StringBuilder();

            List<string> params_ = new List<string>();
            foreach (ast.Identifier p in this.Parameters)
            {
                params_.Add(p.String());
            }

            out_.Append("macro");
            out_.Append("(");
            out_.Append(string.Join(", ", params_));
            out_.Append(") {\n");
            out_.Append(this.Body.String());
            out_.Append("\n}");

            return out_.ToString();
        }
    }
}
